### ISSUE TITLE
Reconfiguration after Firefox-Update 115

### ISSUE THREAD

**Issue by einsq** [jonerrr/mailcow-alias-extension#2]
Great add-on for mailcow. Using it since two weeks without a problem in Firefox. But updating to FF115 i had to do an initial setup of the add-on. Will there always a reconfiguration after every browser backup?

**Comment by jonerrr** [comment]
I ran into the same issue. I wasn't able to find any error logs the last time I debugged this. I will try to fix this when I am back home. If you have any potential solutions I'd appreciate it.

**Comment by einsq** [comment]
Sorry, i have no idea.. :(

**Comment by jonerrr** [comment]
This should be fixed in the latest update (which is currently pending approval). Please let me know if this is still an issue after the new update.
