### ISSUE TITLE
Alias Domain is mangled.

### ISSUE THREAD

**Issue by stelb** [jonerrr/mailcow-alias-extension#7]
Hi,

I have a primary domain whatever.tld for temporary aliases I have setup yolo.whatever.tld.

The extension gets all domains I have and also whatever.tld + yolo.whatever.tld. I select yolo for generating aliases.

But it does not work and I see something like this in the API Log:

`/api/v1/add/alias | POST | IP | attr='{"address":"mahmood+saeli478@yolo.whatever","goto":"me@whatever.tld","active":"1","private_comment":"aliasaddon_2_manage.whatever.tld_1718173355493"}'`

mahmood+saeli478@yolo.whatever is requested, which of course is not accepted.

Sample in preferences looks the same:
zanele-kuznetsova598@yolo.whatever

Can this mangling be removed and just use the domain provided by the API?
There are even domains like in, uk, mx, nz, br that just have at least 3 levels.
Or 2nd level is used for customers, branches, departments whatever.

**Comment by stelb** [comment]
ok, it seems that falso has some simple idea of DNS structures.. (I don't get, how a DNS Name  is split into 'provider' and 'suffix')
At least it was not developed for this usecase here ,)
But it should be working with any level. provider needs to be set, suffix can be empty.

Testing with live editor: https://ngneat.github.io/falso/docs/user

![grafik](https://github.com/jonerrr/mailcow-alias-extension/assets/13351684/bcdf9c0d-583e-4a0f-9533-f3033c6e07db)

splitting is possible at any part, as long as 'provider' is set.

Edit: i messed the dot at the end. So: split at last dot and pass 'yolo.whatever' as provider and 'tld' as suffix.

**Comment by stelb** [comment]
I am no JS Coder, but something like this, is splitting tld off as 'suffix' and the rest into 'provider'
let domain = "yolo.whatever.tld";
const suffix = domain.split(".").pop();
const provider = domain.split(".").slice(0, -1).join(".");

**Comment by jonerrr** [comment]
Hi there, thank you for reporting the issue. I've pushed a fix that will hopefully get published on both extension stores today.

**Comment by stelb** [comment]
Hi! I was able to test it now and it works, as expected.

Thanks! :)
